version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: Your password
      MYSQL_DATABASE: Your Database
    ports:
      - "3336:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: container-app-java
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/Your Database
      SPRING_DATASOURCE_USERNAME: Your username
      SPRING_DATASOURCE_PASSWORD: Your password
    networks:
      - default
volumes:
  mysql_data: