spring:
  profiles:
    active: dev

  application:
    name: java

  datasource:
    url: jdbc:mysql://localhost:3336/{{Your Database}}
    username: Your username
    password: Your password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  jackson:
    serialization:
      write_dates_as_timestamps: false

  security:
    user:
      name: Your username
      password: Your password

  springdoc:
    swagger-ui:
      path: /api-docs

  logging:
    level:
      org.springframework.web: DEBUG